# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestCreateitemtypemapping():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createitemtypemapping(self):
    # Test name: create itemtype mapping
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get(os.environ['WEKO3_HOST'])
    # 2 | setWindowSize | 1646x976 |  | 
    self.driver.set_window_size(1646, 976)
    # 3 | click | linkText=Log in |  | 
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    # 4 | type | id=email | info@inveniosoftware.org | 
    self.driver.find_element(By.ID, "email").send_keys("info@inveniosoftware.org")
    # 5 | type | id=password | uspass123 | 
    self.driver.find_element(By.ID, "password").send_keys("uspass123")
    # 6 | sendKeys | id=password | ${KEY_ENTER} | 
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    # 7 | click | linkText=info@inveniosoftware.org |  | 
    self.driver.find_element(By.LINK_TEXT, "info@inveniosoftware.org").click()
    # 8 | click | linkText=Administration |  | 
    self.driver.find_element(By.LINK_TEXT, "Administration").click()
    # 9 | click | linkText=Item Types |  | 
    self.driver.find_element(By.LINK_TEXT, "Item Types").click()
    # 10 | click | linkText=Mapping |  | 
    self.driver.find_element(By.LINK_TEXT, "Mapping").click()
    # 11 | click | css=.panel > .panel-body |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".panel > .panel-body").click()
    # 12 | click | id=item-type-lists |  | 
    self.driver.find_element(By.ID, "item-type-lists").click()
    # 13 | select | id=item-type-lists | label=data2(1) | 
    dropdown = self.driver.find_element(By.ID, "item-type-lists")
    dropdown.find_element(By.XPATH, "//option[. = 'data2(1)']").click()
    # 14 | click | css=#ul_pubdate > .list_jpcoar_mapping input |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#ul_pubdate > .list_jpcoar_mapping input").click()
    # 15 | click | css=#ul_pubdate > .list_jpcoar_mapping .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#ul_pubdate > .list_jpcoar_mapping .form-control").click()
    # 16 | select | css=#ul_pubdate > .list_jpcoar_mapping .form-control | label=date | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "#ul_pubdate > .list_jpcoar_mapping .form-control")
    dropdown.find_element(By.XPATH, "//option[. = 'date']").click()
    # 17 | click | css=#ul_item_1570959927393 > .list_jpcoar_mapping input |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#ul_item_1570959927393 > .list_jpcoar_mapping input").click()
    # 18 | click | css=#ul_item_1570959927393 > .list_jpcoar_mapping .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#ul_item_1570959927393 > .list_jpcoar_mapping .form-control").click()
    # 19 | select | css=#ul_item_1570959927393 > .list_jpcoar_mapping .form-control | label=title | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "#ul_item_1570959927393 > .list_jpcoar_mapping .form-control")
    dropdown.find_element(By.XPATH, "//option[. = 'title']").click()
    # 20 | click | css=#sub_mapping-add > .glyphicon |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#sub_mapping-add > .glyphicon").click()
    # 21 | mouseOver | css=#sub_mapping-add > .glyphicon |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#sub_mapping-add > .glyphicon")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 22 | mouseOut | css=#sub_mapping-add > .glyphicon |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 23 | click | css=.row:nth-child(3) .col-sm-8 .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) .col-sm-8 .form-control").click()
    # 24 | select | css=.row:nth-child(3) .col-sm-8 .form-control | label=Language | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3) .col-sm-8 .form-control")
    dropdown.find_element(By.XPATH, "//option[. = 'Language']").click()
    # 25 | click | css=#ul_item_1570959939365 > .list_jpcoar_mapping |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#ul_item_1570959939365 > .list_jpcoar_mapping").click()
    # 26 | click | css=#ul_item_1570959939365 > .list_jpcoar_mapping input |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#ul_item_1570959939365 > .list_jpcoar_mapping input").click()
    # 27 | click | css=#ul_item_1570959939365 > .list_jpcoar_mapping .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#ul_item_1570959939365 > .list_jpcoar_mapping .form-control").click()
    # 28 | select | css=#ul_item_1570959939365 > .list_jpcoar_mapping .form-control | label=file | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "#ul_item_1570959939365 > .list_jpcoar_mapping .form-control")
    dropdown.find_element(By.XPATH, "//option[. = 'file']").click()
    # 29 | click | css=.sub_child_list .col-sm-7 .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".sub_child_list .col-sm-7 .form-control").click()
    # 30 | select | css=.sub_child_list .col-sm-7 .form-control | label=file.date | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".sub_child_list .col-sm-7 .form-control")
    dropdown.find_element(By.XPATH, "//option[. = 'file.date']").click()
    # 31 | click | css=.row:nth-child(2) .col-sm-8 .form-control |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(2) .col-sm-8 .form-control").click()
    # 32 | click | id=mapping-submit |  | 
    self.driver.find_element(By.ID, "mapping-submit").click()
    # 33 | click | css=.caret |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".caret").click()
    # 34 | click | linkText=Logout |  | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
  
